notifications:
    slack:
        secure: izOWvKhesHUYRPDkmBMbCXtzBSrCZdzSDacLfHpY33W9NMmeU99u6muOKdXfDj+Tb7bym3yj0s1Z815SMXmuAXoWQyqqGNEWnqc1eJmFfR0DzG9U+bH6hDf0zUJS7UTZ/8232TTkuTVK3zaSE1SHJb0p5z9k822e+Bs9aSpqGcpsrbvBvNQUB1z9p0mGTlp1vMdNAXr2YHizu5eBuS01+3tf/lUhXdr5Y8sC+Vnmpy0gjMwDFfwXdFXAP2HJoCo9eEhhH01fhcp3EXyKCQ6BzUwsFSChIGWFHgLt+bN0C106x74l5jT+11cF3jbsaAVdND/lBZGF3g+WFdJKwfbvBkIKcbKk6fMTN6yYD5jXZ/ZwHNkxeJlVaYae1aJSk5XkbahoKDYZIJ6kY2R2tZjv6+dnY7Oiwo/QxZCWXma3/MGFiOPgnZ9EIaFonv2ShcdNDyWbxA0xwKRtnJYim3y9WTIcdwfj99Ibzj/1O6vx7hLu8QrmgHeNIATZ57/xL5Hrbpgj2sBIYcswaUryCFLJvXxxoG9VpCMA3yMhRh1RL17dxiTDmUIK3CnsPT3mbz/54NiIDZf3lZ3YtzJQs7u4SBQBP2NMHO3TGk1VV+XnmX1zAf6ELlCReIk7l2hGWIkFjkDIvkFG3gr5HRhTPSwZ5HxyRUhyWwGAIHvI/QnKYso=

git:
    depth: 1
    quiet: true
    submodules: false

branches:
    only:
        - master

language: go
go:
    - 1.5.x
    - 1.6.x
    - 1.7.x
    - 1.8.x
    - 1.9.x
    - 1.10.x
    - 1.11.x
    - tip

script:
    - sh .travis.sh

after_success:
    - bash <(curl -s https://codecov.io/bash)
